new guard.mk w/ unit tests

diff --git a/mk/test/Makefile b/mk/test/Makefile
--- a/mk/test/Makefile
+++ b/mk/test/Makefile
@@ -1,18 +1,34 @@
-all: test ;
-
 tests:=$(wildcard *.t)
+
+goals:=$(tests:%.t=%)
 
 output:=$(addsuffix .out,$(tests))
 
-test: $(output)
+.PHONY: all $(goals)
+
+all: $(goals)
+
+$(goals): % : %.t %.t.out Makefile
 
 TEST_MK=test.mk
 
-MAKE_CMD=MAKEFILES='$(TEST_MK)' $(MAKE) -dpf '$<'
+# from main.mk
+PATH.mk			:=$(patsubst %/,%,$(dir \
+	$(patsubst %/,%,$(dir $(realpath $(lastword $(MAKEFILE_LIST)))))\
+))
+
+MAKE_CMD=MAKEFILES='$(TEST_MK)' $(MAKE) -dpf '$<' TEST='$<' PATH.mk='$(PATH.mk)'
 
 $(output): %.out : % Makefile
 	@{\
-		trap "echo 'FAIL'; grep '\*\*\*' '$@'; exit 1" ERR ;\
+		function err_trap () {\
+			echo 'FAIL' ;\
+			grep '\*\*\*' '$@' |\
+				grep -v xIGNOREx ;\
+			mv '$@' '$@.err' ;\
+			exit 1 ;\
+		} ;\
+		trap err_trap ERR ;\
 		echo -ne '$<: ' ;\
 		echo -ne '$(MAKE_CMD)\n\n' > '$@' ;\
 		$(MAKE_CMD) >> '$@' 2>&1 ;\
@@ -21,5 +37,7 @@ $(output): %.out : % Makefile
 
 clean:
 	rm -f *.out
+
+$(tests):: ;
 
 Makefile:: ;
